import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'es' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.shop': 'Tienda',
    'nav.products': 'Productos',
    'nav.allProducts': 'Ver todos los productos',
    'nav.bathroom': 'Para el Baño',
    'nav.home_category': 'Para el Hogar',
    'nav.contact': 'Contacto',
    'nav.ourMethod': 'Nuestro Método',
    'nav.howItWorks': 'Cómo Funciona',
    'nav.howItWorksPoop': 'Cómo funciona Capitan Poop?',
    'nav.howItWorksHome': 'Cómo funciona Capitan Home?',
    'nav.account': 'Cuenta',
    'nav.createAccount': 'Crear Cuenta',
    'nav.login': 'Iniciar Sesión',
    'nav.logout': 'Cerrar Sesión',
    'nav.cart': 'Carrito',
    'nav.wishlist': 'Lista de Deseos',
    'nav.faq': 'Preguntas Frecuentes',
    
    // Hero
    'hero.title': 'Elimina olores al instante, de manera natural y efectiva',
    'hero.subtitle': 'Capitan Poop y Capitan Home: protección diaria para tu baño y tu hogar con ingredientes 100% naturales.',
    'hero.cta1': 'Ver Productos',
    'hero.cta2': 'Compra Ahora',
    'hero.badge': '100% Ingredientes Naturales',
    'hero.mainTitle1': 'Elimina Olores',
    'hero.mainTitle2': 'Naturalmente',
    'hero.description': 'Productos 100% naturales que neutralizan olores en el baño y hogar.',
    'hero.descriptionBold': 'Sin químicos, sin perfumes artificiales.',
    'hero.viewProducts': 'Ver Productos',
    'hero.howItWorks': 'Cómo Funciona',
    'hero.aboutUs': 'Sobre Nosotros',
    'hero.natural': '100% Natural',
    'hero.securePayment': 'Pago Seguro',
    'hero.veryEffective': 'Muy Efectivo',
    
    // Products Section
    'products.featured': 'Nuestros Productos Más Populares',
    'products.all': 'Todos Nuestros Productos',
    'products.addToCart': 'Agregar al Carrito',
    'products.outOfStock': 'Agotado',
    'products.inStock': 'En Stock',
    'products.installments': 'cuotas sin intereses de',
    'products.sale': 'OFERTA',
    'products.addToWishlist': 'Agregar a Favoritos',
    'products.removeFromWishlist': 'Eliminar de Favoritos',
    'products.addedToWishlist': 'Agregado a favoritos',
    'products.removedFromWishlist': 'Eliminado de favoritos',
    
    // How to Use
    'howToUse.title': 'Usarlo es tan fácil como 1, 2, 3',
    'howToUse.step1': 'Agita',
    'howToUse.step1Desc': 'Agita bien antes de usar para activar los aceites esenciales.',
    'howToUse.step2': 'Aplica',
    'howToUse.step2Desc': 'Rocía una capa ligera en el área deseada.',
    'howToUse.step3': 'Disfruta',
    'howToUse.step3Desc': 'Siéntate o disfruta de tu hogar sin malos olores.',
    'howToUse.poopTitle': '¿Cómo se usa Capitan Poop?',
    'howToUse.poopSubtitle': 'El uso de Capitan Poop en tres pasos, para decirle adiós al mal olor del number two.',
    'howToUse.shake': 'Agita',
    'howToUse.shakeDesc': 'Agita bien el producto antes de usar para activar los aceites esenciales.',
    'howToUse.spray': 'Esparse',
    'howToUse.sprayDesc': 'Rocía 2-3 veces sobre el agua del inodoro antes de usar.',
    'howToUse.sit': 'Siéntate',
    'howToUse.sitDesc': '¡Listo! Disfruta de un baño sin malos olores.',
    
    // Trust Section
    'trust.title': 'Compra con tranquilidad',
    'trust.securePayment': 'Pago seguro con tarjetas y efectivo',
    'trust.natural': 'Ingredientes 100% naturales',
    'trust.dataProtection': 'Protección de datos garantizada',
    
    // Social Proof
    'social.title': 'Nuestros clientes felices',
    'social.testimonial1': 'Capitan Poop cambió mi rutina diaria. ¡Ya no hay malos olores!',
    'social.testimonial2': 'Increíble producto. Natural y efectivo. Lo recomiendo 100%.',
    'social.testimonial3': 'Capitan Home es perfecto para eliminar olores del closet. Muy satisfecha.',
    
    // Home Feature Cards
    'home.poopCard': 'Capitan Poop',
    'home.poopCardDesc': 'Para el baño',
    'home.homeCard': 'Capitan Home',
    'home.homeCardDesc': 'Para el hogar',
    'home.naturalCard': '100% Natural',
    'home.naturalCardDesc': 'Sin químicos',
    'home.effectiveCard': 'Efectivo',
    'home.effectiveCardDesc': 'Resultados reales',
    'home.shopByCategory': 'Compra por Categoría',
    'home.shopByCategoryDesc': 'Descubre nuestras dos líneas de productos naturales diseñadas para eliminar olores en diferentes espacios',
    'home.viewProducts': 'Ver productos',
    'home.bathroomEliminatorDesc': 'Eliminador de olores para el baño. Bloquea olores antes de que salgan del agua.',
    'home.homeEliminatorDesc': 'Eliminador de olores para el hogar. Ideal para cocina, closets y espacios cerrados.',
    
    // Contact
    'contact.title': 'Contáctanos',
    'contact.subtitle': 'Estamos aquí para ayudarte. Contáctanos y te responderemos lo antes posible.',
    'contact.name': 'Nombre',
    'contact.email': 'Email',
    'contact.message': 'Mensaje',
    'contact.send': 'Enviar Mensaje',
    'contact.phone': 'Teléfono',
    'contact.businessHours': 'Horario de Atención',
    'contact.monday-friday': 'Lunes - Viernes:',
    'contact.saturday': 'Sábados:',
    'contact.sunday': 'Domingos:',
    'contact.closed': 'Cerrado',
    'contact.whyChooseUs': 'Por Qué Elegirnos',
    'contact.guarantee1': 'Envíos Nacionales',
    'contact.guarantee1desc': 'Entregas en todo el territorio colombiano',
    'contact.guarantee2': 'Ingredientes Naturales',
    'contact.guarantee2desc': '100% naturales y seguros',
    'contact.guarantee3': 'Pago Seguro',
    'contact.guarantee3desc': 'Protegemos tu información',
    'contact.share': 'Comparte nuestra página',
    'contact.linkCopied': '¡Enlace copiado al portapapeles!',
    'contact.instagramCopy': '¡Enlace copiado! Abre Instagram para compartir.',
    'contact.location': 'Ubicación',
    
    // Trust Badges
    'trustBadge.shipping': 'Enviamos tu compra',
    'trustBadge.shippingDesc': 'Entregas a todo el país',
    'trustBadge.payment': 'Paga como quieras',
    'trustBadge.paymentDesc': 'Tarjetas de crédito o efectivo',
    'trustBadge.security': 'Compra con seguridad',
    'trustBadge.securityDesc': 'Tus datos siempre protegidos',
    
    // FAQ
    'faq.title': 'Preguntas Frecuentes',
    'faq.subtitle': 'Encuentra respuestas a las preguntas más comunes sobre nuestros productos',
    'faq.q1': '¿Los productos son realmente naturales?',
    'faq.a1': 'Sí, todos nuestros productos están elaborados con ingredientes 100% naturales. Utilizamos aceites esenciales y extractos vegetales, sin químicos agresivos, parabenos ni alcohol.',
    'faq.q2': 'Hacen envíos a todo el país?',
    'faq.a2': 'Sí, realizamos envíos a toda Colombia. Tu pedido llegará entre 2-5 días hábiles dependiendo de tu ubicación.',
    'faq.q3': '¿Cuánto dura un frasco?',
    'faq.a3': 'Dependiendo del uso, un frasco de 60ml puede durar entre 2-3 meses. Solo necesitas 3-5 gotas por aplicación, lo que hace que el producto sea muy rendidor.',
    'faq.q4': '¿Es seguro para niños y mascotas?',
    'faq.a4': 'Completamente seguro. Al ser 100% natural y sin químicos tóxicos, es apto para toda la familia, incluyendo niños y mascotas. Sin embargo, recomendamos mantenerlo fuera del alcance de los niños.',
    'faq.q5': '¿Cómo funciona el producto?',
    'faq.a5': 'Los aceites esenciales forman una barrera aromática que atrapa los malos olores antes de que se dispersen en el aire. No solo enmascara los olores, sino que los neutraliza de manera natural.',
    'faq.q6': '¿Puedo pagar en cuotas?',
    'faq.a6': 'Sí, aceptamos pagos a través de Mercado Pago con múltiples opciones de cuotas sin intereses. Puedes financiar tu compra en 3, 6, 9 o 12 cuotas según tu preferencia.',
    'faq.q7': '¿Tienen garantía de satisfacción?',
    'faq.a7': 'Sí, si no estás 100% satisfecho con tu compra, ofrecemos devolución del dinero dentro de los primeros 30 días. Tu satisfacción es nuestra prioridad.',
    'faq.q8': '¿Dónde puedo ver cómo usar los productos?',
    'faq.a8': 'Tenemos guías detalladas de uso en nuestras páginas "Cómo funciona Capitan Poop" y "Cómo funciona Capitan Home". También incluimos instrucciones en cada producto.',
    
    // Cart
    'cart.title': 'Tu Carrito',
    'cart.empty': 'Tu carrito está vacío',
    'cart.subtotal': 'Subtotal',
    'cart.total': 'Total',
    'cart.checkout': 'Proceder al Pago',
    'cart.continueShopping': 'Continuar Comprando',
    'cart.remove': 'Eliminar',
    'cart.quantity': 'Cantidad',
    
    // Wishlist
    'wishlist.title': 'Mi Lista de Deseos',
    'wishlist.empty': 'Tu lista de deseos está vacía',
    'wishlist.addedToWishlist': 'Agregado a la lista de deseos',
    'wishlist.removedFromWishlist': 'Eliminado de la lista de deseos',
    'wishlist.addToWishlist': 'Agregar a la lista de deseos',
    'wishlist.removeFromWishlist': 'Eliminar de la lista de deseos',
    'wishlist.moveToCart': 'Mover al carrito',
    'wishlist.continueShopping': 'Continuar Comprando',
    'wishlist.viewProducts': 'Ver Productos',
    
    // Footer
    'footer.newsletter': 'Suscríbete al boletín',
    'footer.subscribe': 'Suscribirse',
    'footer.subscribing': 'Suscribiendo...',
    'footer.copyright': '© 2024 Capitan Poop. Todos los derechos reservados.',
    'footer.quickLinks': 'Enlaces Rápidos',
    
    // Categories
    'category.bathroom': 'Para el Baño',
    'category.home': 'Para el Hogar',
    'category.all': 'Todos',
    
    // Product Detail
    'detail.description': 'Descripción',
    'detail.ingredients': 'Ingredientes',
    'detail.howToUse': 'Cómo usar',
    'detail.natural': '100% Natural',
    
    // How It Works Page
    'howItWorks.poop.title': 'Cómo funciona Capitan Poop',
    'howItWorks.poop.desc': 'Aplica antes de usar el baño y los aceites esenciales bloquean el mal olor al instante.',
    'howItWorks.home.title': 'Cómo funciona Capitan Home',
    'howItWorks.home.desc': 'Rocía en lugares donde se generan malos olores y neutralízalos de manera natural.',
    'howItWorks.ingredients': 'Aceites esenciales y extractos naturales',
    'howItWorks.safety': 'Sin químicos fuertes, apto para toda la familia',
    
    // Auth
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.login': 'Iniciar Sesión',
    'auth.createAccount': 'Crear Cuenta',
    'auth.noAccount': '¿No tienes cuenta?',
    'auth.hasAccount': '¿Ya tienes cuenta?',
    'auth.subtitle': 'Accede a tu cuenta para gestionar tus pedidos',
    'auth.rememberMe': 'Recordarme',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.backToHome': 'Volver al inicio',
    'auth.createAccountSubtitle': 'Crea tu cuenta para disfrutar de todos los beneficios',
    'auth.termsAndConditions': 'Acepto los términos y condiciones y la política de privacidad',
    'auth.phone': 'Teléfono',
    'auth.phonePlaceholder': '+57 321 555 1234',
    'auth.successBenefit': 'Comprá más rápido y llevá el control de tus pedidos, ¡en un solo lugar!',
    'auth.successTitle': '¡Estás a un paso de crear tu cuenta!',
    'auth.successMessage': 'Te enviamos un link a',
    'auth.successMessageEnd': 'para que valides tu email.',
    'auth.resendLink': '¿Todavía no lo recibiste?',
    'auth.resendButton': 'Enviar link de nuevo',
    
    // Account Page
    'account.title': 'Mi Cuenta',
    'account.welcome': 'Bienvenido de nuevo',
    'account.subtitle': 'Gestiona tu información y tus pedidos',
    'account.personalInfo': 'Información Personal',
    'account.name': 'Nombre',
    'account.email': 'Correo Electrónico',
    'account.phone': 'Teléfono',
    'account.editInfo': 'Editar Información',
    'account.saveInfo': 'Guardar Cambios',
    'account.orderHistory': 'Historial de Pedidos',
    'account.noOrders': 'No tienes pedidos todavía',
    'account.startShopping': 'Comenzar a Comprar',
    'account.checkoutBenefit': 'Tu información se guardará automáticamente para hacer tus compras más rápidas en el checkout',
    'account.savedForCheckout': 'Información guardada para el checkout',
    'account.logoutButton': 'Cerrar Sesión',
    
    // Checkout Page
    'checkout.title': 'Finalizar Compra',
    'checkout.shippingInfo': 'Información de Envío',
    'checkout.firstName': 'Nombre',
    'checkout.lastName': 'Apellido',
    'checkout.address': 'Dirección',
    'checkout.city': 'Ciudad',
    'checkout.state': 'Departamento',
    'checkout.zipCode': 'Código Postal',
    'checkout.orderSummary': 'Resumen del Pedido',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping': 'Envío',
    'checkout.freeShipping': 'INCLUIDO',
    'checkout.total': 'Total',
    'checkout.paymentMethod': 'Método de Pago',
    'checkout.creditCard': 'Tarjeta de Crédito/Débito',
    'checkout.mercadoPago': 'Mercado Pago',
    'checkout.pse': 'PSE',
    'checkout.placeOrder': 'Realizar Pedido',
    'checkout.secureCheckout': 'Checkout Seguro',
    'checkout.emptyCart': 'Tu carrito está vacío',
    'checkout.continueShopping': 'Continuar Comprando',
    'checkout.savedInfo': 'Información guardada de tu cuenta',
    'checkout.editInfo': 'Editar',
    'checkout.notLoggedIn': 'Inicia sesión para usar tu información guardada',
    
    // Checkout Steps
    'checkout.steps.cart': 'Carrito',
    'checkout.steps.delivery': 'Entrega',
    'checkout.steps.payment': 'Pago',
    
    // Order Confirmation / Thank You Page
    'orderConfirm.thankYou': '¡Gracias por tu compra',
    'orderConfirm.thankYouGeneral': '¡Gracias por tu compra!',
    'orderConfirm.orderPlaced': 'Tu pedido ha sido confirmado',
    'orderConfirm.orderNumber': 'Número de Pedido',
    'orderConfirm.emailSent': 'Te hemos enviado un correo de confirmación a',
    'orderConfirm.hopeToSeeYou': '¡Esperamos verte pronto!',
    'orderConfirm.comeBackSoon': 'Vuelve pronto por más productos naturales para tu hogar y baño',
    'orderConfirm.backToHome': 'Volver al Inicio',
    'orderConfirm.viewProducts': 'Ver Más Productos',
    'orderConfirm.processing': 'Procesando tu pedido',
    'orderConfirm.shipping': 'Tu pedido será enviado pronto',
    'orderConfirm.contactUs': 'Si tienes alguna pregunta, contáctanos',
    
    // AI Chatbot
    'chatbot.title': 'Asistente Virtual',
    'chatbot.subtitle': 'Disponible 24/7',
    'chatbot.placeholder': 'Escribe tu pregunta...',
    'chatbot.send': 'Enviar',
    'chatbot.minimize': 'Minimizar chat',
    'chatbot.close': 'Cerrar chat',
    'chatbot.open': 'Abrir chat de ayuda',
    'chatbot.typing': 'Escribiendo...',
    'chatbot.greeting': '¡Hola! 👋 Soy tu asistente virtual de Capitán Poop. Estoy aquí para ayudarte 24/7. ¿En qué puedo ayudarte hoy?',
    'chatbot.quickOptions': 'Opciones rápidas:',
    'chatbot.option.products': '🛍️ Ver productos',
    'chatbot.option.howItWorks': '💡 ¿Cómo funciona?',
    'chatbot.option.shipping': '📦 Información de envío',
    'chatbot.option.natural': '🌿 Ingredientes naturales',
    'chatbot.option.contact': '📞 Contacto',
    'chatbot.error': 'Lo siento, algo salió mal. Por favor intenta de nuevo.',
    'chatbot.newChat': 'Nueva conversación',
    
    // Common
    'common.price': 'Precio',
    'common.size': 'Tamaño',
    
    // Products Page Info Section
    'products.infoTitle': 'Capitan Poop y Capitan Home los verdaderos eliminadores de olores',
    'products.poopTitle': 'CAPITAN POOP',
    'products.poopDescription': 'Bloquea los malos olores, creando una capa sobre el agua del inodoro 🚽 Su base natural de aceites esenciales deja en el ambiente un delicioso aroma.',
    'products.poopUsage': 'Se debe aplicar antes de sentarse y hacer popó.',
    'products.homeTitle': 'CAPITAN HOME',
    'products.homeDescription': 'Elimina los malos olores de tu hogar, en armarios, tendidos, sofás, tapetes, zapatos o en todo aquello que huele mal. Solo debe agitarse y rociar al aire o sobre la superficie.',
    'products.homeNatural': 'Es completamente natural',
    
    // Our Method - Capitan Poop
    'method.poop.title': 'Cómo Funciona Capitan Poop',
    'method.poop.subtitle': 'Aplica antes de usar el baño y los aceites esenciales bloquean el mal olor al instante.',
    'method.poop.stepsTitle': 'Usarlo es tan fácil como 1, 2, 3',
    'method.poop.step1': '1. Agita',
    'method.poop.step1Desc': 'Agita bien antes de usar para activar los aceites esenciales.',
    'method.poop.step2': '2. Aplica',
    'method.poop.step2Desc': 'Rocía una capa ligera en el área deseada.',
    'method.poop.step3': '3. Disfruta',
    'method.poop.step3Desc': 'Siéntate o disfruta de tu hogar sin malos olores.',
    'method.poop.scienceTitle': 'La Ciencia Detrás del Producto',
    'method.poop.scienceDesc1': 'Capitan Poop utiliza una fórmula innovadora basada en aceites esenciales naturales que crean una barrera sobre la superficie del agua. Esta barrera atrapa los olores antes de que se liberen al aire, bloqueándolos de manera efectiva.',
    'method.poop.scienceDesc2': 'A diferencia de los ambientadores tradicionales que solo enmascaran los malos olores con fragancias fuertes, Capitan Poop neutraliza los olores en su origen, proporcionando una solución natural y efectiva.',
    'method.poop.ingredientsTitle': 'Ingredientes',
    'method.poop.ingredient1': 'Aceites Esenciales Naturales',
    'method.poop.ingredient1Desc': 'Extraídos de plantas de alta calidad para máxima efectividad.',
    'method.poop.ingredient2': 'Sin Químicos Agresivos',
    'method.poop.ingredient2Desc': 'Sin químicos fuertes, apto para toda la familia',
    'method.poop.ingredient3': 'Biodegradable',
    'method.poop.ingredient3Desc': 'Fórmula amigable con el medio ambiente.',
    'method.poop.ingredient4': 'Seguro para Toda la Familia',
    'method.poop.ingredient4Desc': 'Probado dermatológicamente y seguro para uso diario.',
    'method.poop.benefitsTitle': 'Beneficios',
    'method.poop.benefit1': 'Bloquea olores al instante, no los enmascara',
    'method.poop.benefit2': 'Fórmula 100% natural con aceites esenciales',
    'method.poop.benefit3': 'Fácil de usar - solo 2-3 pulverizaciones',
    'method.poop.benefit4': 'Portátil y discreto - llévalo a donde quieras',
    'method.poop.benefit5': 'Larga duración - hasta 300 usos por botella',
    'method.poop.ctaTitle': '¿Listo para Probarlo?',
    'method.poop.ctaDesc': 'Únete a miles de clientes satisfechos que ya disfrutan de un baño sin malos olores.',
    'method.poop.ctaButton': 'Ver Productos Capitan Poop',
    
    // Our Method - Capitan Home
    'method.home.title': 'Cómo Funciona Capitan Home',
    'method.home.subtitle': 'Rocía en lugares donde se generan malos olores y neutralízalos de manera natural.',
    'method.home.stepsTitle': 'Modo de Uso',
    'method.home.step1': '1. Agita',
    'method.home.step1Desc': 'Agita bien el producto antes de cada uso.',
    'method.home.step2': '2. Rocía',
    'method.home.step2Desc': 'Aplica 3-4 pulverizaciones en el área afectada.',
    'method.home.step3': '3. Disfruta',
    'method.home.step3Desc': 'Los olores desaparecen en segundos.',
    'method.home.whereTitle': '¿Dónde Usar Capitan Home?',
    'method.home.where1': 'Zapatos',
    'method.home.where1Desc': 'Elimina olores de zapatos deportivos, botas y calzado en general.',
    'method.home.where2': 'Closets',
    'method.home.where2Desc': 'Mantén tu armario fresco y libre de olores a humedad.',
    'method.home.where3': 'Sofás y Muebles',
    'method.home.where3Desc': 'Neutraliza olores de mascotas, humo y otros olores persistentes.',
    'method.home.where4': 'Ropa y Textiles',
    'method.home.where4Desc': 'Refresca cortinas, alfombras y prendas sin necesidad de lavar.',
    'method.home.where5': 'Basura',
    'method.home.where5Desc': 'Controla olores en cubos de basura y áreas de reciclaje.',
    'method.home.where6': 'Automóvil',
    'method.home.where6Desc': 'Mantén tu vehículo fresco sin perfumes artificiales.',
    'method.home.formulaTitle': 'Fórmula Avanzada',
    'method.home.formulaIntro': 'Capitan Home utiliza tecnología de neutralización de olores con enzimas naturales y aceites esenciales que:',
    'method.home.formula1': 'Descomponen las moléculas de olor en lugar de solo cubrirlas',
    'method.home.formula2': 'Actúan rápidamente - resultados visibles en segundos',
    'method.home.formula3': 'Son seguros - sin químicos tóxicos ni fragancias artificiales',
    'method.home.formula4': 'No dejan residuos - se secan rápidamente sin manchar',
    'method.home.ingredientsTitle': 'Ingredientes',
    'method.home.ingredient1': '100% Natural',
    'method.home.ingredient1Desc': 'Aceites esenciales y extractos naturales',
    'method.home.ingredient2': 'Probado y Certificado',
    'method.home.ingredient2Desc': 'Fórmula probada dermatológicamente y certificada como segura.',
    'method.home.benefitsTitle': 'Beneficios de Capitan Home',
    'method.home.benefit1': 'Versátil: Úsalo en múltiples superficies y espacios del hogar',
    'method.home.benefit2': 'Seguro: No tóxico, sin alcohol, sin parabenos',
    'method.home.benefit3': 'Efectivo: Neutraliza olores, no los enmascara',
    'method.home.benefit4': 'Económico: Alta concentración - poco producto, grandes resultados',
    'method.home.ctaTitle': 'Transforma tu Hogar Hoy',
    'method.home.ctaDesc': 'Descubre el poder de la neutralización natural de olores con Capitan Home.',
    'method.home.ctaButton': 'Ver Productos Capitan Home',
    
    // About Page
    'about.title': 'Sobre Nosotros',
    'about.subtitle': 'Conoce la historia detrás de Capitan Poop',
    'about.ourStoryTitle': 'Nuestra Historia',
    'about.ourStory1': 'Capitan Poop nació de una necesidad simple pero universal: eliminar los olores desagradables del baño de forma natural y efectiva. Cansados de los ambientadores químicos que solo enmascaran los olores, decidimos crear una solución diferente.',
    'about.ourStory2': 'Nuestra fórmula 100% natural actúa directamente sobre el agua del inodoro, creando una barrera protectora que atrapa los olores antes de que salgan. Sin químicos agresivos, sin fragancias artificiales, solo ingredientes naturales que funcionan.',
    'about.missionTitle': 'Nuestra Misión',
    'about.missionText': 'Proporcionar soluciones naturales y efectivas para eliminar olores en el hogar, mejorando la calidad de vida de nuestros clientes sin comprometer su salud ni el medio ambiente.',
    'about.valuesTitle': 'Nuestros Valores',
    'about.value1Title': '100% Natural',
    'about.value1Desc': 'Ingredientes naturales, sin químicos agresivos ni fragancias artificiales',
    'about.value2Title': 'Efectividad Comprobada',
    'about.value2Desc': 'Productos que realmente funcionan, respaldados por miles de clientes satisfechos',
    'about.value3Title': 'Compromiso Ambiental',
    'about.value3Desc': 'Cuidamos el planeta con fórmulas biodegradables y envases eco-friendly',
    'about.value4Title': 'Innovación Constante',
    'about.value4Desc': 'Desarrollamos nuevas soluciones para diferentes espacios de tu hogar',
    'about.productsTitle': 'Nuestras Líneas de Productos',
    'about.poopLineTitle': 'Capitan Poop',
    'about.poopLineDesc': 'Nuestra línea original diseñada específicamente para el baño. Crea una barrera protectora en el agua que atrapa los olores antes de que salgan, manteniendo tu baño fresco y sin olores desagradables.',
    'about.homeLineTitle': 'Capitan Home',
    'about.homeLineDesc': 'Expandimos nuestra tecnología natural al resto del hogar. Elimina olores en cocina, closets, espacios cerrados y cualquier área que necesite aire fresco sin químicos agresivos.',
    'about.whyNaturalTitle': '¿Por Qué Productos Naturales?',
    'about.whyNatural1': 'Los ambientadores tradicionales contienen químicos que pueden ser perjudiciales para la salud y el medio ambiente.',
    'about.whyNatural2': 'Nuestros productos utilizan aceites esenciales y extractos naturales que neutralizan olores en lugar de enmascararlos.',
    'about.whyNatural3': 'Son seguros para toda la familia, incluyendo niños y mascotas.',
    'about.teamTitle': 'Nuestro Compromiso',
    'about.teamText': 'En Capitan Poop, cada producto es desarrollado pensando en ti y tu familia. Nos comprometemos a ofrecer soluciones naturales, efectivas y accesibles para todos los colombianos.',
    'about.ctaTitle': '¿Listo para probarlo?',
    'about.ctaText': 'Únete a miles de familias colombianas que ya disfrutan de un hogar libre de olores de forma natural',
    'about.ctaButton': 'Ver Productos',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.shop': 'Shop',
    'nav.products': 'Products',
    'nav.allProducts': 'View all products',
    'nav.bathroom': 'For the Bathroom',
    'nav.home_category': 'For the Home',
    'nav.contact': 'Contact',
    'nav.ourMethod': 'Our Method',
    'nav.howItWorks': 'How It Works',
    'nav.howItWorksPoop': 'How does Capitan Poop work?',
    'nav.howItWorksHome': 'How does Capitan Home work?',
    'nav.account': 'Account',
    'nav.createAccount': 'Create Account',
    'nav.login': 'Log In',
    'nav.logout': 'Log Out',
    'nav.cart': 'Cart',
    'nav.wishlist': 'Wishlist',
    'nav.faq': 'Frequently Asked Questions',
    
    // Hero
    'hero.title': 'Eliminate odors instantly, naturally and effectively',
    'hero.subtitle': 'Capitan Poop and Capitan Home: daily protection for your bathroom and home with 100% natural ingredients.',
    'hero.cta1': 'View Products',
    'hero.cta2': 'Buy Now',
    'hero.badge': '100% Natural Ingredients',
    'hero.mainTitle1': 'Eliminate Odors',
    'hero.mainTitle2': 'Naturally',
    'hero.description': '100% natural products that neutralize odors in the bathroom and home.',
    'hero.descriptionBold': 'No chemicals, no artificial fragrances.',
    'hero.viewProducts': 'View Products',
    'hero.howItWorks': 'How It Works',
    'hero.aboutUs': 'About Us',
    'hero.natural': '100% Natural',
    'hero.securePayment': 'Secure Payment',
    'hero.veryEffective': 'Very Effective',
    
    // Products Section
    'products.featured': 'Our Most Popular Products',
    'products.all': 'All Our Products',
    'products.addToCart': 'Add to Cart',
    'products.outOfStock': 'Out of Stock',
    'products.inStock': 'In Stock',
    'products.installments': 'interest-free installments of',
    'products.sale': 'SALE',
    'products.addToWishlist': 'Add to Wishlist',
    'products.removeFromWishlist': 'Remove from Wishlist',
    'products.addedToWishlist': 'Added to Wishlist',
    'products.removedFromWishlist': 'Removed from Wishlist',
    
    // How to Use
    'howToUse.title': 'Using it is as easy as 1, 2, 3',
    'howToUse.step1': 'Shake',
    'howToUse.step1Desc': 'Shake well before use to activate the essential oils.',
    'howToUse.step2': 'Apply',
    'howToUse.step2Desc': 'Spray a light layer in the desired area.',
    'howToUse.step3': 'Enjoy',
    'howToUse.step3Desc': 'Sit or enjoy your home without bad odors.',
    'howToUse.poopTitle': 'How to Use Capitan Poop?',
    'howToUse.poopSubtitle': 'Three steps to say goodbye to bad bathroom odors.',
    'howToUse.shake': 'Shake',
    'howToUse.shakeDesc': 'Shake the product well before use to activate the essential oils.',
    'howToUse.spray': 'Spray',
    'howToUse.sprayDesc': 'Spray 2-3 times over the toilet water before use.',
    'howToUse.sit': 'Sit',
    'howToUse.sitDesc': 'Done! Enjoy a bathroom without bad odors.',
    
    // Trust Section
    'trust.title': 'Shop with confidence',
    'trust.securePayment': 'Secure payment with cards and cash',
    'trust.natural': '100% natural ingredients',
    'trust.dataProtection': 'Guaranteed data protection',
    
    // Social Proof
    'social.title': 'Our happy customers',
    'social.testimonial1': 'Capitan Poop changed my daily routine. No more bad odors!',
    'social.testimonial2': 'Incredible product. Natural and effective. I recommend it 100%.',
    'social.testimonial3': 'Capitan Home is perfect for eliminating closet odors. Very satisfied.',
    
    // Home Feature Cards
    'home.poopCard': 'Capitan Poop',
    'home.poopCardDesc': 'For the bathroom',
    'home.homeCard': 'Capitan Home',
    'home.homeCardDesc': 'For the home',
    'home.naturalCard': '100% Natural',
    'home.naturalCardDesc': 'No chemicals',
    'home.effectiveCard': 'Effective',
    'home.effectiveCardDesc': 'Real results',
    'home.shopByCategory': 'Shop by Category',
    'home.shopByCategoryDesc': 'Discover our two lines of natural products designed to eliminate odors in different spaces',
    'home.viewProducts': 'View products',
    'home.bathroomEliminatorDesc': 'Bathroom odor eliminator. Blocks odors before they come out of the water.',
    'home.homeEliminatorDesc': 'Home odor eliminator. Ideal for kitchen, closets, and enclosed spaces.',
    
    // Contact
    'contact.title': 'Contact Us',
    'contact.subtitle': 'We are here to help you. Contact us and we will respond as soon as possible.',
    'contact.name': 'Name',
    'contact.email': 'Email',
    'contact.message': 'Message',
    'contact.send': 'Send message',
    'contact.phone': 'Phone',
    'contact.businessHours': 'Business Hours',
    'contact.monday-friday': 'Monday - Friday:',
    'contact.saturday': 'Saturdays:',
    'contact.sunday': 'Sundays:',
    'contact.closed': 'Closed',
    'contact.whyChooseUs': 'Why Choose Us',
    'contact.guarantee1': 'Nationwide Shipping',
    'contact.guarantee1desc': 'Deliveries throughout the Colombian territory',
    'contact.guarantee2': 'Natural Ingredients',
    'contact.guarantee2desc': '100% natural and safe',
    'contact.guarantee3': 'Secure Payment',
    'contact.guarantee3desc': 'We protect your information',
    'contact.share': 'Share our page',
    'contact.linkCopied': '¡Link copied to clipboard!',
    'contact.instagramCopy': '¡Link copied! Open Instagram to share.',
    'contact.location': 'Location',
    
    // Trust Badges
    'trustBadge.shipping': 'We ship your purchase',
    'trustBadge.shippingDesc': 'Deliveries to the whole country',
    'trustBadge.payment': 'Pay as you want',
    'trustBadge.paymentDesc': 'Credit cards or cash',
    'trustBadge.security': 'Buy with security',
    'trustBadge.securityDesc': 'Your data is always protected',
    
    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.subtitle': 'Find answers to the most common questions about our products',
    'faq.q1': 'Are the products really natural?',
    'faq.a1': 'Yes, all our products are made with 100% natural ingredients. We use essential oils and vegetable extracts, without harsh chemicals, parabens, or alcohol.',
    'faq.q2': 'Do you ship to the whole country?',
    'faq.a2': 'Yes, we offer shipping to all of Colombia. Your order will arrive between 2-5 business days depending on your location.',
    'faq.q3': 'How long does a bottle last?',
    'faq.a3': 'Depending on usage, a 60ml bottle can last between 2-3 months. You only need 3-5 drops per application, making the product very efficient.',
    'faq.q4': 'Is it safe for children and pets?',
    'faq.a4': 'Completely safe. Being 100% natural and free from toxic chemicals, it is suitable for the whole family, including children and pets. However, we recommend keeping it out of reach of children.',
    'faq.q5': 'How does the product work?',
    'faq.a5': 'Essential oils form an aromatic barrier that traps bad odors before they disperse into the air. It not only masks odors but neutralizes them naturally.',
    'faq.q6': 'Can I pay in installments?',
    'faq.a6': 'Yes, we accept payments through Mercado Pago with multiple interest-free installment options. You can finance your purchase in 3, 6, 9, or 12 installments according to your preference.',
    'faq.q7': 'Do you offer a satisfaction guarantee?',
    'faq.a7': 'Yes, if you are not 100% satisfied with your purchase, we offer a money-back guarantee within the first 30 days. Your satisfaction is our priority.',
    'faq.q8': 'Where can I see how to use the products?',
    'faq.a8': 'We have detailed usage guides on our "How Capitan Poop Works" and "How Capitan Home Works" pages. We also include instructions with each product.',
    
    // Cart
    'cart.title': 'Your Cart',
    'cart.empty': 'Your cart is empty',
    'cart.subtotal': 'Subtotal',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'cart.continueShopping': 'Continue Shopping',
    'cart.remove': 'Remove',
    'cart.quantity': 'Quantity',
    
    // Wishlist
    'wishlist.title': 'My Wishlist',
    'wishlist.empty': 'Your wishlist is empty',
    'wishlist.addedToWishlist': 'Added to wishlist',
    'wishlist.removedFromWishlist': 'Removed from wishlist',
    'wishlist.addToWishlist': 'Add to wishlist',
    'wishlist.removeFromWishlist': 'Remove from wishlist',
    'wishlist.moveToCart': 'Move to cart',
    'wishlist.continueShopping': 'Continue Shopping',
    'wishlist.viewProducts': 'View Products',
    
    // Footer
    'footer.newsletter': 'Subscribe to our newsletter',
    'footer.subscribe': 'Subscribe',
    'footer.subscribing': 'Subscribing...',
    'footer.copyright': '© 2024 Capitan Poop. All rights reserved.',
    'footer.quickLinks': 'Quick Links',
    
    // Categories
    'category.bathroom': 'For the Bathroom',
    'category.home': 'For the Home',
    'category.all': 'All',
    
    // Product Detail
    'detail.description': 'Description',
    'detail.ingredients': 'Ingredients',
    'detail.howToUse': 'How to use',
    'detail.natural': '100% Natural',
    
    // How It Works Page
    'howItWorks.poop.title': 'How Capitan Poop Works',
    'howItWorks.poop.desc': 'Apply before using the bathroom and the essential oils block bad odors instantly.',
    'howItWorks.home.title': 'How Capitan Home Works',
    'howItWorks.home.desc': 'Spray in places where bad odors are generated and neutralize them naturally.',
    'howItWorks.ingredients': 'Essential oils and natural extracts',
    'howItWorks.safety': 'No harsh chemicals, suitable for the whole family',
    
    // Auth
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm password',
    'auth.login': 'Log In',
    'auth.createAccount': 'Create Account',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.subtitle': 'Access your account to manage your orders',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot your password?',
    'auth.backToHome': 'Back to home',
    'auth.createAccountSubtitle': 'Create your account to enjoy all the benefits',
    'auth.termsAndConditions': 'I accept the terms and conditions and privacy policy',
    'auth.phone': 'Phone',
    'auth.phonePlaceholder': '+57 321 555 1234',
    'auth.successBenefit': 'Shop faster and manage your orders in one place!',
    'auth.successTitle': 'You\'re one step away from creating your account!',
    'auth.successMessage': 'We sent a link to',
    'auth.successMessageEnd': 'to validate your email.',
    'auth.resendLink': 'Haven\'t received it yet?',
    'auth.resendButton': 'Send link again',
    
    // Account Page
    'account.title': 'My Account',
    'account.welcome': 'Welcome back',
    'account.subtitle': 'Manage your information and orders',
    'account.personalInfo': 'Personal Information',
    'account.name': 'Name',
    'account.email': 'Email',
    'account.phone': 'Phone',
    'account.editInfo': 'Edit Information',
    'account.saveInfo': 'Save Changes',
    'account.orderHistory': 'Order History',
    'account.noOrders': 'You don\'t have any orders yet',
    'account.startShopping': 'Start Shopping',
    'account.checkoutBenefit': 'Your information will be saved automatically to make your purchases faster at checkout',
    'account.savedForCheckout': 'Information saved for checkout',
    'account.logoutButton': 'Log Out',
    
    // Checkout Page
    'checkout.title': 'Finalize Purchase',
    'checkout.shippingInfo': 'Shipping Information',
    'checkout.firstName': 'First Name',
    'checkout.lastName': 'Last Name',
    'checkout.address': 'Address',
    'checkout.city': 'City',
    'checkout.state': 'Department',
    'checkout.zipCode': 'Zip Code',
    'checkout.orderSummary': 'Order Summary',
    'checkout.subtotal': 'Subtotal',
    'checkout.shipping': 'Shipping',
    'checkout.freeShipping': 'INCLUDED',
    'checkout.total': 'Total',
    'checkout.paymentMethod': 'Payment Method',
    'checkout.creditCard': 'Credit/Debit Card',
    'checkout.mercadoPago': 'Mercado Pago',
    'checkout.pse': 'PSE',
    'checkout.placeOrder': 'Place Order',
    'checkout.secureCheckout': 'Secure Checkout',
    'checkout.emptyCart': 'Your cart is empty',
    'checkout.continueShopping': 'Continue Shopping',
    'checkout.savedInfo': 'Saved information from your account',
    'checkout.editInfo': 'Edit',
    'checkout.notLoggedIn': 'Log in to use your saved information',
    
    // Checkout Steps
    'checkout.steps.cart': 'Cart',
    'checkout.steps.delivery': 'Delivery',
    'checkout.steps.payment': 'Payment',
    
    // Order Confirmation / Thank You Page
    'orderConfirm.thankYou': 'Thank you for your purchase',
    'orderConfirm.thankYouGeneral': 'Thank you for your purchase!',
    'orderConfirm.orderPlaced': 'Your order has been confirmed',
    'orderConfirm.orderNumber': 'Order Number',
    'orderConfirm.emailSent': 'We have sent a confirmation email to',
    'orderConfirm.hopeToSeeYou': 'We hope to see you soon!',
    'orderConfirm.comeBackSoon': 'Come back soon for more natural products for your home and bathroom',
    'orderConfirm.backToHome': 'Back to Home',
    'orderConfirm.viewProducts': 'View More Products',
    'orderConfirm.processing': 'Processing your order',
    'orderConfirm.shipping': 'Your order will be shipped soon',
    'orderConfirm.contactUs': 'If you have any questions, contact us',
    
    // AI Chatbot
    'chatbot.title': 'Virtual Assistant',
    'chatbot.subtitle': 'Available 24/7',
    'chatbot.placeholder': 'Write your question...',
    'chatbot.send': 'Send',
    'chatbot.minimize': 'Minimize chat',
    'chatbot.close': 'Close chat',
    'chatbot.open': 'Open help chat',
    'chatbot.typing': 'Typing...',
    'chatbot.greeting': '¡Hola! 👋 I am your Capitan Poop virtual assistant. I am here to help you 24/7. How can I assist you today?',
    'chatbot.quickOptions': 'Quick options:',
    'chatbot.option.products': '🛍️ View products',
    'chatbot.option.howItWorks': '💡 How does it work?',
    'chatbot.option.shipping': '📦 Shipping information',
    'chatbot.option.natural': '🌿 Natural ingredients',
    'chatbot.option.contact': '📞 Contact us',
    'chatbot.error': 'Sorry, something went wrong. Please try again.',
    'chatbot.newChat': 'New chat',
    
    // Common
    'common.price': 'Price',
    'common.size': 'Size',
    
    // Products Page Info Section
    'products.infoTitle': 'Capitan Poop and Capitan Home the true odor eliminators',
    'products.poopTitle': 'CAPITAN POOP',
    'products.poopDescription': 'Blocks bad odors, creating a layer on the toilet water 🚽 Its natural base of essential oils leaves a delicious aroma in the environment.',
    'products.poopUsage': 'It should be applied before sitting and defecating.',
    'products.homeTitle': 'CAPITAN HOME',
    'products.homeDescription': 'Eliminate bad odors in your home, in closets, bedding, sofas, carpets, shoes or in anything that smells bad. Just shake and spray into the air or onto the surface.',
    'products.homeNatural': 'It is completely natural',
    
    // Our Method - Capitan Poop
    'method.poop.title': 'How Capitan Poop Works',
    'method.poop.subtitle': 'Apply before using the bathroom and the essential oils block bad odors instantly.',
    'method.poop.stepsTitle': 'Using it is as easy as 1, 2, 3',
    'method.poop.step1': '1. Shake',
    'method.poop.step1Desc': 'Shake well before use to activate the essential oils.',
    'method.poop.step2': '2. Apply',
    'method.poop.step2Desc': 'Spray a light layer in the desired area.',
    'method.poop.step3': '3. Enjoy',
    'method.poop.step3Desc': 'Sit or enjoy your home without bad odors.',
    'method.poop.scienceTitle': 'The Science Behind the Product',
    'method.poop.scienceDesc1': 'Capitan Poop uses an innovative formula based on natural essential oils that create a barrier on the water surface. This barrier traps odors before they are released into the air, effectively blocking them.',
    'method.poop.scienceDesc2': 'Unlike traditional air fresheners that only mask bad odors with strong fragrances, Capitan Poop neutralizes odors at their source, providing a natural and effective solution.',
    'method.poop.ingredientsTitle': 'Ingredients',
    'method.poop.ingredient1': 'Natural Essential Oils',
    'method.poop.ingredient1Desc': 'Extracted from high-quality plants for maximum effectiveness.',
    'method.poop.ingredient2': 'No Harsh Chemicals',
    'method.poop.ingredient2Desc': 'No harsh chemicals, suitable for the whole family',
    'method.poop.ingredient3': 'Biodegradable',
    'method.poop.ingredient3Desc': 'Environmentally friendly formula.',
    'method.poop.ingredient4': 'Safe for the Whole Family',
    'method.poop.ingredient4Desc': 'Dermatologically tested and safe for daily use.',
    'method.poop.benefitsTitle': 'Benefits',
    'method.poop.benefit1': 'Blocks odors instantly, doesn\'t mask them',
    'method.poop.benefit2': '100% natural formula with essential oils',
    'method.poop.benefit3': 'Easy to use - just 2-3 sprays',
    'method.poop.benefit4': 'Portable and discreet - take it anywhere',
    'method.poop.benefit5': 'Long-lasting - up to 300 uses per bottle',
    'method.poop.ctaTitle': 'Ready to Try It?',
    'method.poop.ctaDesc': 'Join thousands of satisfied customers who already enjoy a bathroom without bad odors.',
    'method.poop.ctaButton': 'View Capitan Poop Products',
    
    // Our Method - Capitan Home
    'method.home.title': 'How Capitan Home Works',
    'method.home.subtitle': 'Spray in places where bad odors are generated and neutralize them naturally.',
    'method.home.stepsTitle': 'How to Use',
    'method.home.step1': '1. Shake',
    'method.home.step1Desc': 'Shake the product well before each use.',
    'method.home.step2': '2. Spray',
    'method.home.step2Desc': 'Apply 3-4 sprays in the affected area.',
    'method.home.step3': '3. Enjoy',
    'method.home.step3Desc': 'Odors disappear in seconds.',
    'method.home.whereTitle': 'Where to Use Capitan Home?',
    'method.home.where1': 'Shoes',
    'method.home.where1Desc': 'Eliminates odors from sports shoes, boots and footwear in general.',
    'method.home.where2': 'Closets',
    'method.home.where2Desc': 'Keep your closet fresh and free from musty odors.',
    'method.home.where3': 'Sofas and Furniture',
    'method.home.where3Desc': 'Neutralizes pet odors, smoke and other persistent smells.',
    'method.home.where4': 'Clothing and Textiles',
    'method.home.where4Desc': 'Refresh curtains, carpets and garments without washing.',
    'method.home.where5': 'Garbage',
    'method.home.where5Desc': 'Control odors in trash cans and recycling areas.',
    'method.home.where6': 'Automobile',
    'method.home.where6Desc': 'Keep your vehicle fresh without artificial perfumes.',
    'method.home.formulaTitle': 'Advanced Formula',
    'method.home.formulaIntro': 'Capitan Home uses odor neutralization technology with natural enzymes and essential oils that:',
    'method.home.formula1': 'Break down odor molecules instead of just covering them',
    'method.home.formula2': 'Act quickly - visible results in seconds',
    'method.home.formula3': 'Are safe - no toxic chemicals or artificial fragrances',
    'method.home.formula4': 'Leave no residue - dry quickly without staining',
    'method.home.ingredientsTitle': 'Ingredients',
    'method.home.ingredient1': '100% Natural',
    'method.home.ingredient1Desc': 'Essential oils and natural extracts',
    'method.home.ingredient2': 'Tested and Certified',
    'method.home.ingredient2Desc': 'Dermatologically tested formula and certified as safe.',
    'method.home.benefitsTitle': 'Benefits of Capitan Home',
    'method.home.benefit1': 'Versatile: Use on multiple surfaces and spaces in the home',
    'method.home.benefit2': 'Safe: Non-toxic, alcohol-free, paraben-free',
    'method.home.benefit3': 'Effective: Neutralizes odors, doesn\'t mask them',
    'method.home.benefit4': 'Economical: High concentration - little product, great results',
    'method.home.ctaTitle': 'Transform Your Home Today',
    'method.home.ctaDesc': 'Discover the power of natural odor neutralization with Capitan Home.',
    'method.home.ctaButton': 'View Capitan Home Products',
    
    // About Page
    'about.title': 'About Us',
    'about.subtitle': 'Learn the story behind Capitan Poop',
    'about.ourStoryTitle': 'Our Story',
    'about.ourStory1': 'Capitan Poop was born from a simple but universal need: to eliminate unpleasant bathroom odors naturally and effectively. Tired of chemical air fresheners that only mask odors, we decided to create a different solution.',
    'about.ourStory2': 'Our 100% natural formula acts directly on the toilet water, creating a protective barrier that traps odors before they escape. Without harsh chemicals, without artificial fragrances, only natural ingredients that work.',
    'about.missionTitle': 'Our Mission',
    'about.missionText': 'Provide natural and effective solutions to eliminate odors at home, improving the quality of life of our customers without compromising their health or the environment.',
    'about.valuesTitle': 'Our Values',
    'about.value1Title': '100% Natural',
    'about.value1Desc': 'Natural ingredients, without harsh chemicals or artificial fragrances',
    'about.value2Title': 'Proven Effectiveness',
    'about.value2Desc': 'Products that really work, backed by thousands of satisfied customers',
    'about.value3Title': 'Environmental Commitment',
    'about.value3Desc': 'We care for the planet with biodegradable formulas and eco-friendly packaging',
    'about.value4Title': 'Constant Innovation',
    'about.value4Desc': 'We develop new solutions for different spaces in your home',
    'about.productsTitle': 'Our Product Lines',
    'about.poopLineTitle': 'Capitan Poop',
    'about.poopLineDesc': 'Our original line specifically designed for the bathroom. Creates a protective barrier in the water that traps odors before they escape, keeping your bathroom fresh and free from unpleasant odors.',
    'about.homeLineTitle': 'Capitan Home',
    'about.homeLineDesc': 'We expand our natural technology to the rest of the home. Eliminate odors in the kitchen, closets, enclosed spaces, and any area that needs fresh air without harsh chemicals.',
    'about.whyNaturalTitle': 'Why Natural Products?',
    'about.whyNatural1': 'Traditional air fresheners contain chemicals that can be harmful to health and the environment.',
    'about.whyNatural2': 'Our products use essential oils and natural extracts that neutralize odors instead of masking them.',
    'about.whyNatural3': 'They are safe for the whole family, including children and pets.',
    'about.teamTitle': 'Our Commitment',
    'about.teamText': 'At Capitan Poop, each product is developed with you and your family in mind. We commit to offering natural, effective, and accessible solutions for all Colombians.',
    'about.ctaTitle': 'Ready to try it?',
    'about.ctaText': 'Join thousands of Colombian families who already enjoy a home free of odors in a natural way',
    'about.ctaButton': 'View Products',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('es');

  const toggleLanguage = () => {
    setLanguage(prev => prev === 'es' ? 'en' : 'es');
  };

  const t = (key: string): string => {
    const translation = translations[language][key as keyof typeof translations.es];
    if (typeof translation === 'string') {
      return translation;
    }
    // Fallback to the key itself if translation not found
    return key;
  };

  const value = { language, toggleLanguage, t };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextType {
  const context = useContext(LanguageContext);
  if (!context) {
    // During hot reload, provide a fallback instead of throwing
    if (import.meta.hot) {
      return {
        language: 'es',
        toggleLanguage: () => {},
        t: (key: string) => key
      };
    }
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}